version: '3.4'

services:
  php:
    image: ${CONTAINER_REGISTRY_BASE}/php
    container_name: wow-collection-php
    build:
      context: ./api
      target: api_platform_php
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - ./api:/srv/api:rw,cached
      - ./logs/api:/api/var/log

  api:
    image: ${CONTAINER_REGISTRY_BASE}/nginx
    container_name: wow-collection-api
    build:
      context: ./api/
      dockerfile: Dockerfile.prod
      target: api_platform_nginx
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - php
    volumes:
      - ./api/public:/srv/api/public:ro
      - ./logs/api_nginx:/var/log/nginx
    ports:
      - '127.0.0.1:8052:80'

  cache-proxy:
    image: ${CONTAINER_REGISTRY_BASE}/varnish
    container_name: wow-collection-cache-proxy
    build:
      context: ./api
      target: api_platform_varnish
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/php
        - ${CONTAINER_REGISTRY_BASE}/nginx
        - ${CONTAINER_REGISTRY_BASE}/varnish
    depends_on:
      - api
    volumes:
      - ./api/docker/varnish/conf:/usr/local/etc/varnish:ro
    tmpfs:
      - /usr/local/var/varnish:exec
    ports:
      - "127.0.0.1:8053:80"

  db:
    image: postgres:9.6-alpine
    container_name: wow-collection-db
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api-platform
      - POSTGRES_PASSWORD=9Ri23oJsbgcroj3lxs9k
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw

  website:
      build: './website'
      container_name: wow-collection-website
      volumes:
          - './website:/app'
      working_dir: '/app'
      command: 'yarn start'
      ports:
          - "127.0.0.1:8054:3000"

  elk:
    image: willdurand/elk
    container_name: wow-collection-elk
    volumes:
      - ./elk/logstash:/etc/logstash
      - ./elk/logstash/patterns:/opt/logstash/patterns
      - ./logs/api:/api/var/log
      - ./logs/api_nginx:/var/log/nginx
#      - ./logs/website_nginx:/application/log/website_nginx
#      - ./logs/website:/application/log/website
    ports:
      - "127.0.0.1:8055:80"
